config/routes.rb
Rails.application.routes.draw do

  resources :businesses

  resources :lists

  

  devise_for :users
  
  get 'user_root', to: 'businesses#index'
  
  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ApplicationRecord
	belongs_to :user

	belongs_to :list

	validates  :name, presence: true 

	validates  :description,	length: { minimum: 5 } 
end

app/models/list.rb
class List < ApplicationRecord
	has_many   :businesses, dependent: :destroy
	belongs_to :user
	validates :name, presence: true
	validates_presence_of :user
	validate :list_validate


  private

  def list_validate
  	self.errors.add(:lists, 'too much') if self.user.lists.size > 9
  end
end 

app/models/user.rb
class User < ApplicationRecord
  has_many :lists	
  has_many :businesses, through: :lists
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController

  def index
  	@businesses = Business.all
  	@lists = List.all
  end 

  def show
  	@business = Business.find(params[:id])
  end

  def new 
  	@business = Business.new
  end

  def edit
     @business = Business.find params[:id]
  end

  def create
  	@business = Business.new(business_params)
    @business.user_id = current_user.id
  	if @business.save 
  	  redirect_to action: "index"
    else
      render 'new'
    end
  end

  def update
  @business = Business.find(params[:id])
 
  if @business.update(business_params)
    redirect_to @business
  else
    render 'edit'
  end
end

def destroy
  @business = Business.find(params[:id])
  @business.destroy
 
  redirect_to businesses_path
end

private
  def business_params
    params.require(:business).permit(:name, :status, :description, :priority, :user_id, :list_id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index	
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def show
  	@list = List.find(params[:id])
  end

  def new
  	@list = List.new
  end

  def create
	@list = List.new(list_params)
	@list.user_id = current_user.id
	if @list.save 
  	  redirect_to businesses_path
    else
      render 'new'
    end
  end

  def destroy
  	@list = List.find(params[:id])
  	@list.destroy
 
    redirect_to businesses_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  	@user = current_user
  end

  def new
    @user = User.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/businesses/edit.html.erb
<%= form_with model: @business, local: true do |form| %>
 
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@business.errors.count, "error") %> prohibited
        this business from being saved:
      </h2>
      <ul>
        <% @business.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.label :list_id %><br>
    <%= form.collection_select :list_id, List.order(:name), :id, :name %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>To Do</title>
</head>
<body link="red">

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="businesses">To Do</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="businesses/new">New bussines</a></li>
        <li><a href="lists/new">New list</a></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><a <%= link_to 'Log out', destroy_user_session_path, :method => :delete %></a></li>     
      </ul>
    </div>
  </div>
</nav>


<div class="row">
<% @lists.each do |list| %>
    <div class="col-sm-4">
      <table class = "table table-hover">
        <th><%= link_to "#{list.name}", list_path(list) %></th>
        <% list.businesses.each do |business| %>

          <tr>
            <td><%= link_to "#{business.name}", business_path(business) %></td>
            <td><%= business.status %></td>
            <td><%= business.priority %></td>
            <td><%= business.description %></td>
            <td><%= link_to image_tag("edit.png", size: "18x15"), edit_business_path(business) %></td>
            <td><%= link_to image_tag("destroy.png", size: "18x15"), business_path(business),
                                  method: :delete,
                                  data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </table>
    </div>
<% end %>
</div>
</body>
</html>

app/views/businesses/new.html.erb
<%= form_with model: @business, local: true do |form| %>
 
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@business.errors.count, "error") %> prohibited
        this business from being saved:
      </h2>
      <ul>
        <% @business.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.label :list_id %><br>
    <%= form.collection_select :list_id, current_user.lists.order(:name), :id, :name %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/businesses/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @business.name %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @business.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @business.status %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @business.priority %>
</p>


<%= link_to 'Back', businesses_path %>

app/views/home/index.html.erb
<% if user_signed_in? %>
    <span>Здравствуйте, <%= current_user.email %></span>
    <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
    <p><%= link_to 'К списку дел', businesses_path %></p>
<% else %>
    <%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/new.html.erb
<%= form_with model: @list, local: true do |form| %>
 
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@list.errors.count, "error") %> prohibited
        this list from being saved:
      </h2>
      <ul>
        <% @list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.submit %>
  </p>
  <% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<%= link_to 'Back', businesses_path %>
<%= link_to 'Delete', list_path(@list),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %>

<table>
   
  <% @list.businesses.each do |business| %>
    <tr>
      <td><%= business.name %></td>
      <td><%= business.status %></td>
      <td><%= business.priority %></td>
      <td><%= business.description %></td>
      <td><%= link_to 'Show', business_path(business) %></td>
      <td><%= link_to 'Edit', edit_business_path(business) %></td>
      <td><%= link_to 'Destroy', business_path(business),
                                  method: :delete,
                                  data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>

</table>


<div id="myDIV" class="header">
  <h2><%= @list.name %></h2>
  <input type="text" id="myInput" placeholder="Title...">
  <span onclick="newElement()" class="addBtn">Add</span>
</div>

<ul id="myUL">

  <% @list.businesses.each do |business| %>

  <li>
    <%= business.name %>
    <span class="close"> <%= link_to 'x', business_path(business),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %>
                      </span>
  </li>

  <% end %>
</ul>